export const healthCases = [
  {
    id: 'acute-asthma',
    title: 'Acute Asthma',
    system: 'Respiratory',
    status: 'new',
    progress: 0,
    color: 'blue',
    patient: 'Chidinma, 19 years',
    location: 'Emergency bay',
    priority: 'High',
    presentation: 'Wheeze, chest tightness, speaking in short phrases after exposure to dust.',
    vitals: { hr: 118, bp: '118/76', rr: 30, spo2: 91, temp: 37.1 },
    focus: 'Assess airway, breathing, severity, and response to bronchodilator therapy.',
    nextStep: 'Give high-flow oxygen and nebulized salbutamol, then reassess work of breathing.',
    tasks: ['Classify severity', 'Start immediate treatment', 'Reassess after intervention'],
  },
  {
    id: 'diabetic-ketoacidosis',
    title: 'Diabetic Ketoacidosis',
    system: 'Endocrine',
    status: 'new',
    progress: 0,
    color: 'red',
    patient: 'Tunde, 24 years',
    location: 'Acute medical unit',
    priority: 'Critical',
    presentation: 'Polyuria, vomiting, abdominal pain, deep breathing, and missed insulin doses.',
    vitals: { hr: 124, bp: '96/60', rr: 28, spo2: 97, temp: 37.8 },
    focus: 'Recognize dehydration, acidosis, potassium risk, and insulin timing.',
    nextStep: 'Start isotonic fluids, check potassium, and prepare fixed-rate insulin after labs.',
    tasks: ['Identify DKA signs', 'Prioritize fluids', 'Monitor potassium'],
  },
  {
    id: 'hypertensive-emergency',
    title: 'Hypertensive Emergency',
    system: 'Cardiovascular',
    status: 'new',
    progress: 0,
    color: 'purple',
    patient: 'Mrs. Okafor, 58 years',
    location: 'Triage room',
    priority: 'High',
    presentation: 'Severe headache, blurred vision, chest discomfort, and very high blood pressure.',
    vitals: { hr: 96, bp: '218/124', rr: 22, spo2: 96, temp: 36.9 },
    focus: 'Differentiate urgency from emergency by checking for acute target-organ damage.',
    nextStep: 'Assess neurological status, ECG, urine, creatinine, and chest symptoms before lowering BP.',
    tasks: ['Check end-organ signs', 'Choose monitored care', 'Avoid rapid overcorrection'],
  },
  {
    id: 'sepsis-screen',
    title: 'Sepsis Screen',
    system: 'Infectious Disease',
    status: 'new',
    progress: 0,
    color: 'green',
    patient: 'Aisha, 42 years',
    location: 'Ward review',
    priority: 'High',
    presentation: 'Fever, confusion, productive cough, low blood pressure, and reduced urine output.',
    vitals: { hr: 132, bp: '88/54', rr: 32, spo2: 89, temp: 39.2 },
    focus: 'Use early warning signs to trigger oxygen, cultures, antibiotics, fluids, and monitoring.',
    nextStep: 'Escalate care, give oxygen, take cultures, and start broad-spectrum antibiotics promptly.',
    tasks: ['Recognize sepsis', 'Start bundle actions', 'Escalate deterioration'],
  },
  {
    id: 'anaemia-workup',
    title: 'Anaemia Workup',
    system: 'Haematology',
    status: 'new',
    progress: 0,
    color: 'tan',
    patient: 'Ibrahim, 33 years',
    location: 'Outpatient clinic',
    priority: 'Routine',
    presentation: 'General outpatient review for possible anaemia.',
    vitals: { hr: 92, bp: '112/70', rr: 18, spo2: 99, temp: 36.8 },
    focus: 'Connect symptoms, indices, reticulocytes, bleeding history, and nutrition.',
    nextStep: 'Request full blood count with indices, reticulocytes, ferritin, and stool/bleeding history.',
    tasks: ['Classify anaemia', 'Ask bleeding history', 'Plan initial tests'],
  },
  {
    id: 'malaria-child',
    title: 'Febrile Child',
    system: 'Paediatrics',
    status: 'new',
    progress: 0,
    color: 'yellow',
    patient: 'Simi, 6 years',
    location: 'Children emergency room',
    priority: 'Moderate',
    presentation: 'Fever, chills, poor feeding, headache, and one episode of vomiting.',
    vitals: { hr: 122, bp: '94/62', rr: 24, spo2: 98, temp: 38.7 },
    focus: 'Assess danger signs, hydration, malaria testing, and differential diagnosis.',
    nextStep: 'Check danger signs, test for malaria, assess hydration, and treat fever safely.',
    tasks: ['Screen danger signs', 'Order rapid test', 'Assess hydration'],
  },
];

export const clinicalSchedule = [
  { time: '08:30', caseId: 'sepsis-screen', station: 'Triage escalation' },
  { time: '09:15', caseId: 'acute-asthma', station: 'Emergency treatment' },
  { time: '10:00', caseId: 'diabetic-ketoacidosis', station: 'Acute care plan' },
];

export const clinicalSteps = [
  {
    id: 'primary-survey',
    skill: 'Immediate safety',
    prompt: 'The patient looks breathless and anxious. What comes first?',
    answer: 'Use an ABCDE approach and correct immediate airway or breathing threats.',
    options: [
      'Ask for full social history before touching equipment.',
      'Use an ABCDE approach and correct immediate airway or breathing threats.',
      'Wait for all laboratory results before any intervention.',
    ],
    note: 'Clinical reasoning starts with danger first: airway, breathing, circulation, disability, exposure.',
    consequence: 'The team stabilizes the first threat before narrowing the diagnosis.',
    review: 'You kept the first move safe. In acute care, sequence matters because a correct diagnosis can still be unsafe if urgent threats are delayed.',
  },
  {
    id: 'red-flag',
    skill: 'Escalation judgement',
    prompt: 'Which finding should trigger urgent escalation?',
    answer: 'Hypotension, confusion, low oxygen saturation, or rapidly worsening work of breathing.',
    options: [
      'Hypotension, confusion, low oxygen saturation, or rapidly worsening work of breathing.',
      'A stable patient asking many questions.',
      'A long medication list without symptoms.',
    ],
    note: 'Red flags matter because deterioration can outrun a slow diagnostic plan.',
    consequence: 'Senior help is called early and deterioration is treated as time-sensitive.',
    review: 'The key habit is separating routine symptoms from danger signs that change urgency, location of care, and monitoring.',
  },
  {
    id: 'reassessment',
    skill: 'Closing the loop',
    prompt: 'After initial treatment, what should the learner do next?',
    answer: 'Reassess vitals, symptoms, response, and safety before deciding disposition.',
    options: [
      'Discharge immediately because a treatment was given.',
      'Ignore vital signs if the patient says they feel better.',
      'Reassess vitals, symptoms, response, and safety before deciding disposition.',
    ],
    note: 'A treatment is not complete until response and risk have been checked.',
    consequence: 'The patient is reviewed again before discharge, admission, or escalation is chosen.',
    review: 'Reassessment is the safety net. It catches non-response, complications, and patients who looked better for only a moment.',
  },
];

export const clinicalTools = [
  {
    id: 'abcde',
    title: 'ABCDE Check',
    detail: 'Airway, breathing, circulation, disability, and exposure keep urgent care structured.',
  },
  {
    id: 'vitals',
    title: 'Vitals Interpreter',
    detail: 'Look for patterns, not isolated numbers: shock, respiratory distress, fever, and hypoxia.',
  },
  {
    id: 'differentials',
    title: 'Differential Builder',
    detail: 'List likely, dangerous, and easily missed causes before narrowing the diagnosis.',
  },
  {
    id: 'med-safety',
    title: 'Medication Safety',
    detail: 'Check allergies, dose, route, renal/hepatic concerns, pregnancy, and interactions.',
  },
  {
    id: 'handover',
    title: 'SBAR Handover',
    detail: 'Situation, background, assessment, recommendation: concise escalation language.',
  },
  {
    id: 'patient-education',
    title: 'Patient Education',
    detail: 'Explain warning signs, follow-up, medication use, and when to return urgently.',
  },
];
