export const lawCases = [
  {
    id: 'criminal-trial',
    title: 'Criminal Trial',
    type: 'Criminal',
    status: 'in-progress',
    progress: 60,
    color: 'red',
    jurisdiction: 'High Court of Lagos State',
    parties: 'State v. Musa Bello',
    room: 'Courtroom 3',
    nextStep: 'Cross-examine the investigating police officer.',
    facts: 'The accused is charged with robbery. The prosecution relies on eyewitness identification, a recovered phone, and a confessional statement.',
    skill: 'Test identification evidence and voluntariness of confession.',
    statute: 'Evidence Act 2011; Administration of Criminal Justice Act 2015',
    tasks: ['Review the charge', 'Object to weak identification', 'Cross-examine the officer'],
  },
  {
    id: 'constitutional-rights',
    title: 'Constitutional Rights',
    type: 'Public Law',
    status: 'in-progress',
    progress: 40,
    color: 'blue',
    jurisdiction: 'Federal High Court',
    parties: 'Amina Yusuf v. Inspector-General of Police',
    room: 'Courtroom 1',
    nextStep: 'Choose the reliefs for unlawful detention.',
    facts: 'A student activist was detained for six days without charge after a peaceful protest.',
    skill: 'Frame fundamental-rights arguments and remedies.',
    statute: 'Constitution of the Federal Republic of Nigeria 1999, sections 35 and 46',
    tasks: ['Identify breached rights', 'Draft reliefs', 'Argue urgency'],
  },
  {
    id: 'contract-dispute',
    title: 'Contract Dispute',
    type: 'Commercial',
    status: 'in-progress',
    progress: 25,
    color: 'green',
    jurisdiction: 'Lagos State High Court',
    parties: 'Emeka & Co. v. ABC Foods Ltd',
    room: 'Courtroom 2',
    nextStep: 'Advise whether repudiation is available.',
    facts: 'A supplier delivered late for three months after a written time-is-of-essence clause was added to the contract.',
    skill: 'Read clauses, remedies, and commercial correspondence.',
    statute: 'Common law principles on breach, damages, and termination',
    tasks: ['Find the operative clause', 'Assess breach', 'Recommend remedy'],
  },
  {
    id: 'client-interview',
    title: 'Client Interview',
    type: 'Practice Skills',
    status: 'new',
    progress: 5,
    color: 'purple',
    jurisdiction: 'Legal clinic intake',
    parties: 'Client: Blessing Okoro',
    room: 'Interview Room',
    nextStep: 'Ask open questions before legal advice.',
    facts: 'A tenant says the landlord removed her door after she disputed a sudden rent increase.',
    skill: 'Gather facts, screen urgency, and identify client goals.',
    statute: 'Professional ethics and client-care duties',
    tasks: ['Confirm identity', 'Build timeline', 'Identify urgent relief'],
  },
  {
    id: 'evidence-lab',
    title: 'Evidence Lab',
    type: 'Evidence',
    status: 'in-progress',
    progress: 30,
    color: 'orange',
    jurisdiction: 'Trial preparation room',
    parties: 'Evidence review: State v. Danladi',
    room: 'Evidence Desk',
    nextStep: 'Decide which exhibit is admissible.',
    facts: 'The file contains CCTV stills, hearsay messages, a signed statement, and chain-of-custody gaps.',
    skill: 'Separate relevance, admissibility, and weight.',
    statute: 'Evidence Act 2011',
    tasks: ['Tag exhibits', 'Spot hearsay', 'Prepare objection'],
  },
  {
    id: 'negotiation-room',
    title: 'Negotiation Room',
    type: 'ADR',
    status: 'new',
    progress: 0,
    color: 'tan',
    jurisdiction: 'Multi-door courthouse',
    parties: 'Kwara Logistics Ltd v. Northline Stores',
    room: 'ADR Room',
    nextStep: 'Make a settlement offer with fallback terms.',
    facts: 'A supply dispute can settle if payment timing and future delivery guarantees are agreed.',
    skill: 'Balance client interests, BATNA, and principled concessions.',
    statute: 'Lagos Multi-Door Courthouse practice principles',
    tasks: ['Set objectives', 'Make offer', 'Record terms'],
  },
  {
    id: 'moot-court',
    title: 'Moot Court',
    type: 'Advocacy',
    status: 'in-progress',
    progress: 10,
    color: 'teal',
    jurisdiction: 'Court of Appeal simulation',
    parties: 'FRN v. Okafor',
    room: 'Appeal Panel',
    nextStep: 'Answer a bench question on burden of proof.',
    facts: 'The appellant challenges conviction on circumstantial evidence and alleged misdirection by the trial judge.',
    skill: 'Structure appellate submissions under pressure.',
    statute: 'Criminal procedure and appellate review principles',
    tasks: ['State issue', 'Cite record', 'Answer bench'],
  },
  {
    id: 'property-land',
    title: 'Property & Land Dispute',
    type: 'Property',
    status: 'in-progress',
    progress: 15,
    color: 'yellow',
    jurisdiction: 'Customary Court of Appeal pathway',
    parties: 'Ojo Family v. Adewale Family',
    room: 'Courtroom 4',
    nextStep: 'Identify title documents and traditional history evidence.',
    facts: 'Two families claim the same parcel through competing grants and long possession.',
    skill: 'Compare root of title, possession, and documentary evidence.',
    statute: 'Land law principles and customary evidence',
    tasks: ['Trace title', 'Compare plans', 'Prepare issue list'],
  },
];

export const courtroomSchedule = [
  { time: '10:00 AM', caseId: 'criminal-trial', hearing: 'Cross-examination' },
  { time: '11:30 AM', caseId: 'constitutional-rights', hearing: 'Urgent rights application' },
  { time: '2:00 PM', caseId: 'contract-dispute', hearing: 'Interlocutory application' },
];

export const courtroomSteps = [
  {
    id: 'appearance',
    prompt: 'The matter is called. What should counsel do first?',
    answer: 'Announce appearance and identify the party represented.',
    options: [
      'Announce appearance and identify the party represented.',
      'Start cross-examining the witness immediately.',
      'Ask the registrar to mark exhibits before the judge speaks.',
    ],
    note: 'Courtroom order starts with appearance and permission from the bench.',
  },
  {
    id: 'objection',
    prompt: 'The witness starts repeating what a neighbour told him. What is the best move?',
    answer: 'Object and explain that the answer is hearsay unless an exception applies.',
    options: [
      'Let the answer continue because all oral testimony is admissible.',
      'Object and explain that the answer is hearsay unless an exception applies.',
      'Ask the witness to speak louder.',
    ],
    note: 'A good objection names the rule and gives the judge a clear reason.',
  },
  {
    id: 'closing',
    prompt: 'At the end of evidence, what should closing address?',
    answer: 'Tie each issue to admissible evidence and the burden of proof.',
    options: [
      'Repeat every fact in the file without structure.',
      'Ask for sympathy because the client is anxious.',
      'Tie each issue to admissible evidence and the burden of proof.',
    ],
    note: 'Strong advocacy connects facts, issues, law, and remedy.',
  },
];

export const courtroomTools = [
  {
    id: 'objection-guide',
    title: 'Objection Guide',
    detail: 'Use when evidence is irrelevant, hearsay, leading in examination-in-chief, or lacks foundation.',
  },
  {
    id: 'evidence-rules',
    title: 'Evidence Rules',
    detail: 'Check relevance, admissibility, maker/authentication, and weight before tendering an exhibit.',
  },
  {
    id: 'procedure-checklist',
    title: 'Procedure Checklist',
    detail: 'Confirm appearance, pending applications, witness order, exhibits, objections, and closing points.',
  },
  {
    id: 'courtroom-etiquette',
    title: 'Courtroom Etiquette',
    detail: 'Stand when addressing the court, seek leave before moving, and keep submissions concise.',
  },
  {
    id: 'citations-helper',
    title: 'Citations Helper',
    detail: 'Prefer direct statutory provisions and binding authority before persuasive commentary.',
  },
  {
    id: 'full-toolkit',
    title: 'Full Toolkit',
    detail: 'A combined checklist for advocacy, evidence, procedure, and client-protection notes.',
  },
];
